export interface Product {
  id: string
  name: string
  price: number
  originalPrice?: number
  image: string
  category: 'earrings' | 'bangles' | 'accessories' | 'jewelry' | 'saree' | 'lehenga'
  isNew?: boolean
  isOnSale?: boolean
  inStock?: boolean       // false = out of stock but still visible to buyers
  hidden?: boolean        // true = completely hidden from storefront
  href: string
  description?: string
  sizes?: string[]
}

export const trendingProducts: Product[] = [
  {
    id: '1',
    name: 'Kundan Drop Earrings',
    price: 45,
    originalPrice: 65,
    image: '/images/jewelry-earrings-1.jpg',
    category: 'earrings',
    isNew: true,
    isOnSale: true,
    inStock: false,
    href: '/product/1',
    description: 'Handcrafted Kundan drop earrings with intricate gold-plated detailing. Perfect for weddings and festive occasions.',
  },
  {
    id: '2',
    name: 'Gold Polki Bangle Set',
    price: 89,
    image: '/images/jewelry-bangles-1.jpg',
    category: 'bangles',
    isNew: true,
    href: '/product/2',
    description: 'Set of 4 gold-plated Polki bangles with delicate enamel work. A timeless addition to any bridal look.',
    sizes: ['2.4', '2.6', '2.8'],
  },
  {
    id: '3',
    name: 'Pearl Jhumka Earrings',
    price: 38,
    originalPrice: 52,
    image: '/images/jewelry-earrings-1.jpg',
    category: 'earrings',
    isNew: false,
    isOnSale: true,
    href: '/product/3',
    description: 'Classic pearl jhumka earrings with gold-tone finish. Lightweight and elegant for everyday wear.',
  },
  {
    id: '4',
    name: 'Silk Embroidered Dupatta',
    price: 55,
    image: '/images/accessory-scarf-1.jpg',
    category: 'accessories',
    isNew: true,
    href: '/product/4',
    description: 'Pure silk dupatta with hand-embroidered gold zari border. Versatile styling for sarees and lehengas.',
  },
  {
    id: '5',
    name: 'Meenakari Bangle Set',
    price: 72,
    originalPrice: 95,
    image: '/images/jewelry-bangles-1.jpg',
    category: 'bangles',
    isOnSale: true,
    inStock: false,
    href: '/product/5',
    description: 'Vibrant Meenakari enamel bangles in traditional Rajasthani style. Set of 6.',
    sizes: ['2.4', '2.6', '2.8'],
  },
  {
    id: '6',
    name: 'Emerald Chandbali Earrings',
    price: 62,
    image: '/images/jewelry-earrings-1.jpg',
    category: 'earrings',
    isNew: true,
    href: '/product/6',
    description: 'Statement chandbali earrings with emerald green stones and gold-plated setting.',
  },
  {
    id: '7',
    name: 'Maang Tikka with Pearls',
    price: 34,
    originalPrice: 48,
    image: '/images/accessory-bindi-1.jpg',
    category: 'accessories',
    isOnSale: true,
    href: '/product/7',
    description: 'Delicate maang tikka with freshwater pearls and gold-tone chain. Bridal and festive wear.',
  },
  {
    id: '8',
    name: 'Antique Gold Kada',
    price: 115,
    image: '/images/jewelry-bracelet-1.jpg',
    category: 'bangles',
    isNew: true,
    href: '/product/8',
    description: 'Heavy antique gold-finish kada with intricate floral engravings. A statement bridal piece.',
    sizes: ['S', 'M', 'L'],
  },
]

export const earringsProducts: Product[] = [
  {
    id: 'e1',
    name: 'Kundan Drop Earrings',
    price: 45,
    originalPrice: 65,
    image: '/images/jewelry-earrings-1.jpg',
    category: 'earrings',
    isNew: true,
    isOnSale: true,
    href: '/product/e1',
    description: 'Handcrafted Kundan drop earrings with intricate gold-plated detailing.',
  },
  {
    id: 'e2',
    name: 'Pearl Jhumka Earrings',
    price: 38,
    originalPrice: 52,
    image: '/images/jewelry-earrings-1.jpg',
    category: 'earrings',
    isOnSale: true,
    inStock: false,
    href: '/product/e2',
    description: 'Classic pearl jhumka earrings with gold-tone finish.',
  },
  {
    id: 'e3',
    name: 'Emerald Chandbali Earrings',
    price: 62,
    image: '/images/jewelry-earrings-1.jpg',
    category: 'earrings',
    isNew: true,
    href: '/product/e3',
    description: 'Statement chandbali earrings with emerald green stones.',
  },
  {
    id: 'e4',
    name: 'Ruby Stud Earrings',
    price: 29,
    image: '/images/jewelry-earrings-1.jpg',
    category: 'earrings',
    href: '/product/e4',
    description: 'Elegant ruby stud earrings with gold-plated setting.',
  },
  {
    id: 'e5',
    name: 'Polki Dangler Earrings',
    price: 78,
    originalPrice: 99,
    image: '/images/jewelry-earrings-1.jpg',
    category: 'earrings',
    isOnSale: true,
    href: '/product/e5',
    description: 'Luxurious Polki dangler earrings for bridal occasions.',
  },
  {
    id: 'e6',
    name: 'Oxidised Silver Jhumkas',
    price: 22,
    image: '/images/jewelry-earrings-1.jpg',
    category: 'earrings',
    isNew: true,
    href: '/product/e6',
    description: 'Boho-chic oxidised silver jhumkas with tribal motifs.',
  },
]

export const banglesProducts: Product[] = [
  {
    id: 'b1',
    name: 'Gold Polki Bangle Set',
    price: 89,
    image: '/images/jewelry-bangles-1.jpg',
    category: 'bangles',
    isNew: true,
    href: '/product/b1',
    description: 'Set of 4 gold-plated Polki bangles with delicate enamel work.',
    sizes: ['2.4', '2.6', '2.8'],
  },
  {
    id: 'b2',
    name: 'Meenakari Bangle Set',
    price: 72,
    originalPrice: 95,
    image: '/images/jewelry-bangles-1.jpg',
    category: 'bangles',
    isOnSale: true,
    href: '/product/b2',
    description: 'Vibrant Meenakari enamel bangles in traditional Rajasthani style. Set of 6.',
    sizes: ['2.4', '2.6', '2.8'],
  },
  {
    id: 'b3',
    name: 'Antique Gold Kada',
    price: 115,
    image: '/images/jewelry-bracelet-1.jpg',
    category: 'bangles',
    isNew: true,
    href: '/product/b3',
    description: 'Heavy antique gold-finish kada with intricate floral engravings.',
    sizes: ['S', 'M', 'L'],
  },
  {
    id: 'b4',
    name: 'Crystal Glass Bangles',
    price: 18,
    image: '/images/jewelry-bangles-1.jpg',
    category: 'bangles',
    href: '/product/b4',
    description: 'Set of 12 crystal glass bangles in assorted colours.',
    sizes: ['2.4', '2.6', '2.8'],
  },
  {
    id: 'b5',
    name: 'Kundan Bangle Set',
    price: 95,
    originalPrice: 125,
    image: '/images/jewelry-bangles-1.jpg',
    category: 'bangles',
    isOnSale: true,
    inStock: false,
    href: '/product/b5',
    description: 'Bridal Kundan bangle set with pearl drops. Set of 4.',
    sizes: ['2.4', '2.6', '2.8'],
  },
  {
    id: 'b6',
    name: 'Rose Gold Filigree Bangles',
    price: 55,
    image: '/images/jewelry-bangles-1.jpg',
    category: 'bangles',
    isNew: true,
    href: '/product/b6',
    description: 'Delicate rose gold filigree bangles. Set of 2.',
    sizes: ['2.4', '2.6', '2.8'],
  },
]

export const accessoriesProducts: Product[] = [
  {
    id: 'a1',
    name: 'Silk Embroidered Dupatta',
    price: 55,
    image: '/images/accessory-scarf-1.jpg',
    category: 'accessories',
    isNew: true,
    href: '/product/a1',
    description: 'Pure silk dupatta with hand-embroidered gold zari border.',
  },
  {
    id: 'a2',
    name: 'Maang Tikka with Pearls',
    price: 34,
    originalPrice: 48,
    image: '/images/accessory-bindi-1.jpg',
    category: 'accessories',
    isOnSale: true,
    href: '/product/a2',
    description: 'Delicate maang tikka with freshwater pearls and gold-tone chain.',
  },
  {
    id: 'a3',
    name: 'Embroidered Potli Bag',
    price: 42,
    image: '/images/accessory-hand-jewelry-1.jpg',
    category: 'accessories',
    isNew: true,
    href: '/product/a3',
    description: 'Hand-embroidered potli bag with gold thread work. Perfect for weddings.',
  },
  {
    id: 'a4',
    name: 'Kundan Nath (Nose Ring)',
    price: 28,
    image: '/images/accessory-bindi-1.jpg',
    category: 'accessories',
    href: '/product/a4',
    description: 'Traditional Kundan nath with pearl drop. Bridal and festive wear.',
  },
  {
    id: 'a5',
    name: 'Embroidered Hair Pins Set',
    price: 15,
    originalPrice: 22,
    image: '/images/accessory-hand-jewelry-1.jpg',
    category: 'accessories',
    isOnSale: true,
    href: '/product/a5',
    description: 'Set of 6 embroidered hair pins with floral motifs.',
  },
  {
    id: 'a6',
    name: 'Beaded Waist Belt',
    price: 48,
    image: '/images/accessory-scarf-1.jpg',
    category: 'accessories',
    isNew: true,
    href: '/product/a6',
    description: 'Handcrafted beaded waist belt (kamarband) for lehengas and sarees.',
  },
]

export const allProducts: Product[] = [
  ...trendingProducts,
  ...earringsProducts,
  ...banglesProducts,
  ...accessoriesProducts,
].filter((p, index, self) => self.findIndex((x) => x.id === p.id) === index)
